author: DL88250@gmail.com
description: A Web-based IDE for Teams using Golang.

filesets:
    depth: 10
    includes:
        - conf
        - doc
        - i18n
        - static
        - views
        - README.md
        - LICENSE
    excludes:
        - \.git
settings:
        targetdir: ""
        build: |
            test -d Godeps && go(){ godep go "$@";} ; go install -v
        outfiles:
            - wide
